d sudo: false

language: node_js

node_js:
  - '6'

cache:
  bundler: true
  directories:
    - node_modules
    - assets/vendor

before_install:
  - mkdir .travis
  - openssl aes-256-cbc -K $encrypted_3fce5a723986_key -iv $encrypted_3fce5a723986_iv
    -in deploy.key.enc -out .travis/deploy.key -d
  - rvm install 2.3.1

install:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gem install bundler
  - bundle install

script:
  - npm build

deploy:
  provider: script
  script: _bin/deploy.sh
  on:
    branch: master

branches:
  only:
  - master

env:
  global:
    - RESET=true
    - GH_REF=git@github.com:NottinghamSRN/Main-Website.git
