d sudo: false

language: node_js

node_js:
  - '6'

cache:
  bundler: true
  directories:
    - node_modules
    - assets/vendor

before_install:
  - rvm install 2.3.1

install:
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install
  - gem install bundler
  - bundle install
  - curl -o _bin/htmltest https://github.com/wjdp/htmltest/releases/download/v0.4.0/htmltest-linux

script:
  - npm run build
  - _bin/htmltest

deploy:
  provider: script
  script: _bin/deploy.sh
  skip_cleanup: true
  on:
    branch: master

branches:
  only:
  - master

env:
  global:
    - RESET=true
    - GH_REF=git@github.com:NottinghamSRN/NottinghamSRN.git
