# Site settings
language:               "en-GB"
title:                  "Nottingham SRN"
description: >
  The SCRUBS research network (SRN) is a tool created by the SCRUBS Nottingham University Surgical Society
  to create a research mentorship scheme, whereby surgeons can gain assistance with projects they are running, 
  and students can gain valuable research experience.
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  # - "_pages"

exclude:
  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "/.travis/"

# Plugins
gems:             ["jekyll-sitemap", "jekyll-paginate"]

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink: pretty

collections:
  posts:
    permalink:        "/blog/:year/:title/"
    paginate_path:    "/blog/page:num"
    paginate:         5
  pages:
    permalink: /:path/
    output: true
  projects:
    permalink: projects/:path/
    output: true

defaults:
  # Projects
  - scope:
      path: ""
      type: projects
    values:
      layout: project

  # Pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page


compress_html:
  ignore:
    envs: [development]
